apiVersion : apps/v1
kind: Deployment
metadata:
  name: jenkins
  namespace: cicd
  labels:
    app : jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
      - name: jenkin
        image: semenyakin/nginx:v0.1.2
        ports:
        - containerPort: 8080